language: go
go: 
 - 1.11.x

sudo : required


env : 
  - GO111MODULE=on

install : 
  - echo "install"


script : 
 - echo "script"
 - go test -v ./...
 - go build -o geteosaccount .

 deploy:
  provider: releases
  api_key: e59503369344ed21b3e20d30d33c22dbdc3ae0d0
  file: geteosaccount
  skip_cleanup: true
  on:
    tags: true
